### ISSUE TITLE
Send events to redis from a cronjob

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-data-services#189]
Currently we try to send events to redis and also write to the DB in case redis is not available. Then we periodically check if any events were not able to be sent and have accumulated in postgres and try to resend them.

We also have to keep deleting events from postgres that were successfully sent.

We should clean this up and write all events to postgres and then periodically flush them to redis via a cronjob. We should extend the functionality of the existing cronjob that syncs with Keycloak to do this as well.

**Comment by leafty** [comment]
This would delay event sending more than necessary, I am not sure it is a desirable change.

**Comment by leafty** [comment]
@Panaetius @olevski Like stated, above this will delay messages by up to two minutes, which I don't think is acceptable. Why not use background task from Sanic for this specific purpose (sending messages to redis)?

See: https://sanic.dev/en/guide/basics/tasks.md

**Comment by Panaetius** [comment]
like we discussed a while back, it shouldn't be a cronjob so this issue is poorly worded.
A background task raised some concerns about taking up async runtime from dealing with regular requests (I personally don't think this becomes a concern any time soon, though) and stability (a catastrophic error in one fails both pieces).
For now I've just made a draft that has the message sending as a separate container that sends it every 1 second, but using the same image as we use for keycloak sync cronjob. So having one image for all our background needs that can run different jobs based on the container arg.

**Comment by Panaetius** [comment]
btw. in current, deployed data svc it's already a sanic background job, just every 30 secs and only if sending a message failed: https://github.com/SwissDataScienceCenter/renku-data-services/blob/main/bases/renku_data_services/data_api/main.py#L98
Having a separate container on k8s just for this may be a bit nicer but does increase complexity a bit as well

**Comment by leafty** [comment]
If there is a concern about starving server worker process with background tasks, we can start a dedicated non-server worker for this. See: https://sanic.dev/en/guide/running/manager.md#background-tasks

**Comment by Panaetius** [comment]
that's neat, I didn't know about that :+1:

**Comment by leafty** [comment]
@Panaetius Here is a basic POC which can be expanded -> https://github.com/SwissDataScienceCenter/renku-data-services/pull/214

**Comment by Panaetius** [comment]
I don't think using a multiprocessing queue is workable for delivery guarantees. It has to be through postgres and in the same transaction as entities that are changed to properly guarantee that messages are delivered at least once. At least unless we want some two-phase commit that makes everything else more complicated.

Also I'd really appreciate it if you would talk to the person assigned first before working on an issue that already has an assignee.

**Comment by leafty** [comment]
I'm not saying the messages should not be stored on the database, but rather that the trigger for processing can be done and handled from a IPC queue to ensure fast delivery to redis (except when it is down).

**Comment by Panaetius** [comment]
so you're proposing essentially keeping the current approach of saving to database, then sending the message (just through ipc and then redis instead of redis directly) and deleting from the DB if it worked, with the same safety job that resend messages if delivery failed that we have now?

I don't see how that has any meaningful difference over sending it to redis directly as we do now. Other than IPC being slightly faster so reducing latency of requests a bit, but sending to Redis is already not a huge bottleneck (it takes like 5 ms).

If instead you just save (entity and message) to db directly and return, and the background job picks up messages from the db and sends them every 1 second, you still get very reasonable delivery times, but with less complexity and less logic needed to ensure consistency (the db transaction takes care of that).

**Comment by leafty** [comment]
My suggestion is to move the background job which is sending pending messages to redis from a separate container into a non-server process in the same container.

You will still have a regular check for late messages to be sent, but you can also have an immediate path by using a trigger message to that process. The contents of the messages to be sent to Redis are not going through the IPC queue.

This concept should require very minimal changes from what you have now because it's almost the same concept, except that there is a path for sending messages almost instantaneously.

**Comment by Panaetius** [comment]
and I'm saying that if we have a background job that sends messages from DB periodically with a low enough period, that's good enough for us without needing that added complexity of the fast path for a minor latency gain. Things like more logic in the request/decorator for creating messages, dealing with concurrency between "fast" and "slow" path to not send messages twice if possible, less cognitive load on what goes on in general.
As mentioned, I don't think there's a difference between sending to redis directly and having a late message job, versus sending to ipc directly which sends to redis directly and having a late message job, except for an additional layer of indirection. 
Whereas I prefer to have the late message job handle everything and requests just storing to the db. Then there's only one way for a message to go, less moving pieces, at the cost of a message taking like a second to be delivered (we can always tweak this if we need less) vs 10ms with your suggestion, which I think is something we can live with and is perfectly good enough for our use-cases.

**Comment by leafty** [comment]
Fine then.
