### ISSUE TITLE
CRC: Restrict access to the default resource pool

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-data-services#31]
In some cases we want users to not have access to the default resource pool. An example of such a situation is when a resource pool is set up to better control the resources consumed by a large class or workshop. We want to be able to simply not give those users the option of using the default pool. 

How this is set is up to the implementation, but it seems that the natural place would be a flag in the user model on the CRC service.

**Comment by Panaetius** [comment]
use a custom role for users that aren't allowed to access default resource pools

**Comment by olevski** [comment]
@Panaetius I discussed this with @rokroskar . 

It is easier to add a role or flag on the users table in the CRC service rather than in keycloak. So lets do that instead of adding a keycloak role. Then in the future if we need to we can migrate to using keycloak roles. But for now this will be easier to setup and it is easy to implement.

**Comment by rokroskar** [comment]
We should evaluate the urgency of this - I believe it would be great and informative for the cases where set up resource pools for orgs because without pinning users to a pool, we will have a hard time understanding the usage patterns.  But our current model is to charge per reservation not per usage anyway, which makes it less of a concern.
