### ISSUE TITLE
cannot remove tolerations or affinities with PUT/PATCH on resource class

### ISSUE THREAD

**Issue by leafty** [SwissDataScienceCenter/renku-data-services#95]
See [`update_resource_class()`](https://github.com/SwissDataScienceCenter/renku-data-services/blob/main/components/renku_data_services/crc/db.py#L416).

**Comment by aledegano** [comment]
I reopen the issue because it is still not possible to remove tolerations/affinities through `PATCH` this results in a bug in the UI where if you try to delete them the process will seemingly complete successfully, while in reality nothing will change.
I am not sure if this problem needs to be addressed in the frontend or the backend though...
